# Generated by Django 5.2 on 2025-04-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pool_share', models.DecimalField(decimal_places=4, help_text='Fraction of revenue (0–1)', max_digits=5)),
                ('target_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performance_score', models.DecimalField(decimal_places=4, help_text='0–1', max_digits=5)),
                ('last_year_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
