# Generated by Django 5.2 on 2025-04-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTrendFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_category', models.CharField(help_text="E.g., 'Strong Growth', 'Stable', 'Decline'", max_length=50)),
                ('adjustment_factor', models.DecimalField(decimal_places=4, help_text='Multiplier for merit increase', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='is_mrt',
            field=models.BooleanField(default=False, help_text='Material Risk Taker flag'),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(blank=True, help_text='Seniority level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='performance_rating',
            field=models.CharField(blank=True, help_text="E.g., 'Exceeds Expectations', 'Meets Expectations'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, help_text='Job title/function', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MeritMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.CharField(max_length=50)),
                ('compa_ratio_range', models.CharField(help_text="E.g., 'Q1', 'Q2', 'Q3', 'Q4'", max_length=50)),
                ('increase_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'unique_together': {('performance_rating', 'compa_ratio_range')},
            },
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('role', 'level')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='employees.team'),
        ),
        migrations.CreateModel(
            name='KpiAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('investment_performance', models.DecimalField(decimal_places=4, help_text='Achievement percentage', max_digits=5)),
                ('risk_management', models.DecimalField(decimal_places=4, help_text='Achievement percentage', max_digits=5)),
                ('aum_revenue', models.DecimalField(decimal_places=4, help_text='Achievement percentage', max_digits=5)),
                ('qualitative', models.DecimalField(decimal_places=4, help_text='Achievement percentage', max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_achievements', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeamRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='employees.team')),
            ],
            options={
                'unique_together': {('team', 'year')},
            },
        ),
    ]
