# Generated by Django 5.2 on 2025-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_revenuetrendfactor_team_employee_is_mrt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('performance_weight', models.DecimalField(decimal_places=2, default=0.4, max_digits=3)),
                ('revenue_weight', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('min_bonus_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_bonus_percent', models.DecimalField(decimal_places=2, default=200, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
