# Generated by Django 5.2 on 2025-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_compensationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
