# Generated by Django 5.2 on 2025-04-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='employees.datasnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pool_share', models.DecimalField(decimal_places=4, max_digits=5)),
                ('target_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performance_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('last_year_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mrt', models.BooleanField(default=False)),
                ('performance_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.IntegerField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.datasnapshot')),
            ],
        ),
    ]
