# Generated by Django 5.2 on 2025-04-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_datasnapshot_configsnapshot_employeesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('results_cache', models.JSONField(blank=True, null=True)),
                ('base_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='employees.datasnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioEmployeeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mrt', models.BooleanField(blank=True, null=True)),
                ('base_salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_bonus_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discretionary_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage adjustment to calculated compensation', max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overrides', to='employees.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'employee')},
            },
        ),
    ]
