# Generated by Django 5.2 on 2025-04-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_scenario_scenarioemployeeoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.scenario')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('results_cache', models.JSONField(blank=True, null=True)),
                ('comparison_scenarios', models.ManyToManyField(related_name='comparison_items', through='employees.ComparisonItem', to='employees.scenario')),
                ('primary_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_comparisons', to='employees.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.scenariocomparison'),
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('results_cache', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about changes in this version', null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='employees.scenario')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('scenario', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='scenariocomparison',
            name='primary_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_comparisons', to='employees.scenarioversion'),
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.scenarioversion'),
        ),
        migrations.AlterUniqueTogether(
            name='comparisonitem',
            unique_together={('comparison', 'scenario', 'version')},
        ),
    ]
