# Generated by Django 5.2 on 2025-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_comparisonitem_scenariocomparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
